#!/bin/sh

ENABLED=yes
PROCS=bashbot.sh
ARGS=""
PREARGS="dtach -n /opt/var/bashbot.socket"
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
